[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./test" }, { access = "read-write", path = "./script/output" }]
optimizer = true
optimizer_runs = 200
solc-version = "0.8.20"
verbosity = 4

[fmt]
line_length = 80

[rpc_endpoints]
local = "http://localhost:8545"
sepolia = "${SEPOLIA_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"

mainnet = "${MAINNET_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_KEY}" }
baseSepolia = { key = "${ETHERSCAN_KEY}" }

mainnet = { key = "${ETHERSCAN_KEY}" }
base = { key = "${ETHERSCAN_KEY}" }
