[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./test"}]
optimizer = true
optimizer_runs = 200
solc-version = "0.8.20"
verbosity = 4

[fmt]
line_length = 80

[rpc_endpoints]
local = "http://localhost:8545"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
# arbitrum = { key = "${ETHERSCAN_KEY}" }
# arbitrum-goerli = { key = "${ETHERSCAN_KEY}" }
